language: ruby
sudo: false
cache: bundler
rvm:
  - jruby-1.7
  - jruby-9.0.5.0
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
matrix:
  include:
    - rvm: jruby-head
      jdk: oraclejdk8
  allow_failures:
    - rvm: jruby-head